#!/usr/bin/expect -f  
 log_user 2
 set ip [lindex $argv 0 ]
 set port [lindex $argv 1 ]
 set user [lindex $argv 2 ]
 set pass [lindex $argv 3 ]
 send  "echo $argc\n"
 set timeout 60  
 spawn ssh root@$ip -p $port 
 expect {  
 "*yes/no" { send "yes\r"; exp_continue}  
 "*password:" { send "$pass\r" }  
 }  
 expect "#*"
 send  "cp /root/data/common/mgectl /root/data/common/mgectl.bk\r"
 send  "exit\r"  
 expect eof  
